GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/xml
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI1ZGQzOWE3MTBkZmY1ODBjZjZhODgiLCJpYXQiOjE2MzkzMTQzMTB9.z-Kx_O1ShTkWtSixUGbvpTC4OEBLX7ybddI0ikQLtCU